server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: user-service-route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: startup-service-route
          uri: lb://STARTUP-SERVICE
          predicates:
            - Path=/startups/**

        - id: investment-service-route
          uri: lb://INVESTMENT-SERVICE
          predicates:
            - Path=/investments/**

        - id: auth-service-route
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: founderlink-super-secret-key-2024-minimum-32chars

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/api-docs
      - name: User Service
        url: /users/api-docs
      - name: Startup Service
        url: /startups/api-docs
      - name: Investment Service
        url: /investments/api-docs
  api-docs:
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
